chore(ap): Bump assets parachain to `polkadot-v1.10.0`
r0gue-io/assets-parachain pull request #4
Opened 2024-05-22 16:35 UTC by al3mart

Bump dependencies and move pallet configuration to assets module.

2024-05-23 10:37 UTC, brunopgalvao requested changes

2024-05-23 10:37 UTC, brunopgalvao commented on README.md
> +# Base Parachain Template
```suggestion
# Assets Parachain Template
```

2024-05-23 10:37 UTC, brunopgalvao commented on README.md
> +A new [Cumulus](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus)-based Substrate node.
```suggestion
A new [Cumulus](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus)-based Substrate node, configured with fungible and non-fungilble asset functionalities, including asset fractionalization.
```

2024-05-23 10:37 UTC, brunopgalvao commented on README.md
> -This project is a fork of the [Base Parachain Template](https://github.com/r0gue-io/base-parachain).
Keep this.

2024-05-24 07:31 UTC, brunopgalvao approved these changes

2024-06-10 14:57 UTC, AlexD10S commented on network.toml
This shouldn't be included right? pop-cli will generate this file.

2024-06-10 15:10 UTC, AlexD10S approved these changes

2024-06-10 15:12 UTC, AlexD10S requested changes
The `network.toml `shouldn't be included right? `pop-cli` will generate this file.

2024-06-10 15:15 UTC, AlexD10S commented
@brunopgalvao apologies for removing your approval by mistake; could you please approve it again?

2024-06-10 16:32 UTC, al3mart commented
> The `network.toml `shouldn't be included right? `pop-cli` will generate this file.

You are right! Our contracts-parachain template needs addressing as well, then.

2024-06-10 16:40 UTC, AlexD10S approved these changes

2024-06-11 11:14 UTC, merged